# Generated by Django 6.0.5 on 2026-05-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTORegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form20_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('rto_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('registered', 'Registered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rto_registration', to='sales.vehiclesalesorder')),
            ],
            options={
                'verbose_name_plural': 'RTO Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NumberPlateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('issued', 'Issued')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='number_plate_order', to='rto.rtoregistration')),
            ],
            options={
                'verbose_name_plural': 'Number Plate Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
