# Generated by Django 6.0.5 on 2026-05-25 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('issued', 'Issued to Customer')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rto_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rc_book', to='rto.rtoregistration')),
            ],
            options={
                'verbose_name_plural': 'RC Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
