# Generated by Django 6.0.5 on 2026-05-25 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0002_rcbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcbook',
            name='hp_bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rcbook',
            name='hp_endorsed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RegPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rto_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_payments', to='rto.rtoregistration')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='RTOIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_from', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rto_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='rto.rtoregistration')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
