# Generated by Django 6.0.5 on 2026-07-10 18:55
# Hand-edited: reordered into a safe Create -> data-migrate -> Remove sequence
# so existing RTOPayment/RegpayCreation rows are carried over into their new
# child-table rows instead of being silently dropped (same pattern used for
# Phase 2's job_card CharField->FK conversion and Phase 5's VAS rename).

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_rows_to_items(apps, schema_editor):
    RTOPayment = apps.get_model('rto', 'RTOPayment')
    RTOPaymentItem = apps.get_model('rto', 'RTOPaymentItem')
    RegpayCreation = apps.get_model('rto', 'RegpayCreation')
    RegpayCreationItem = apps.get_model('rto', 'RegpayCreationItem')

    for payment in RTOPayment.objects.all():
        item_total = (payment.flag_amount or 0) + (payment.fine_amount or 0) + (payment.license_amount or 0)
        RTOPaymentItem.objects.create(
            payment=payment,
            sales_order_id=payment.sales_order_id,
            flag_amount=payment.flag_amount,
            fine_amount=payment.fine_amount,
            license_amount=payment.license_amount,
            total_amount=item_total,
        )
        payment.total_amount = item_total
        payment.save(update_fields=['total_amount'])

    for regpay in RegpayCreation.objects.all():
        item_amount = (regpay.profit or 0) + (regpay.amount_from_customer or 0)
        RegpayCreationItem.objects.create(
            regpay=regpay,
            sales_order_id=regpay.sales_order_id,
            vehicle_type_id=regpay.vehicle_type_id,
            profit=regpay.profit,
            amount_from_customer=regpay.amount_from_customer,
            amount=item_amount,
        )
        regpay.total_amount = item_amount
        regpay.save(update_fields=['total_amount'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_discountpercentagemaster_ledgercreationdatemaster'),
        ('rto', '0004_registernumbermaster_registrationarea_and_more'),
        ('sales', '0016_vehiclesalesorder_order_form_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegpayCreationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('amount_from_customer', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('regpay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rto.regpaycreation')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regpay_creation_items', to='sales.vehiclesalesorder')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regpay_creation_items', to='rto.regpaybaseamount', verbose_name='Vehicle Type (Base Amount)')),
            ],
            options={
                'verbose_name_plural': 'Regpay Creation Items',
            },
        ),
        migrations.CreateModel(
            name='RTOPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('license_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rto_payment_items', to='accounts.branch')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rto.rtopayment')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rto_payment_items', to='sales.vehiclesalesorder')),
            ],
            options={
                'verbose_name_plural': 'RTO Payment Items',
            },
        ),
        migrations.RunPython(migrate_existing_rows_to_items, noop_reverse),
        migrations.RemoveField(
            model_name='regpaycreation',
            name='amount_from_customer',
        ),
        migrations.RemoveField(
            model_name='regpaycreation',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='regpaycreation',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='regpaycreation',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='rtopayment',
            name='fine_amount',
        ),
        migrations.RemoveField(
            model_name='rtopayment',
            name='flag_amount',
        ),
        migrations.RemoveField(
            model_name='rtopayment',
            name='license_amount',
        ),
        migrations.RemoveField(
            model_name='rtopayment',
            name='sales_order',
        ),
        migrations.AlterField(
            model_name='regpaycreation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sum of item row amounts', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rtopayment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sum of item row totals', max_digits=10),
        ),
    ]
