# Generated by Django 6.0.7 on 2026-07-14 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0005_remove_regpaycreation_amount_from_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberreceiptentrycreation',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='numberreceiptentrycreation',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='numberreceiptentrycreation',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
