# Generated by Django 6.0.1 on 2026-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0006_alter_numberreceiptentrycreation_cgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rchandover',
            name='vehicle_received',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5),
        ),
    ]
