# Generated by Django 6.0.1 on 2026-07-22 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0007_alter_rchandover_vehicle_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberreceiptentrycreation',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='numberreceiptentrycreation',
            name='sgst',
        ),
        migrations.AddField(
            model_name='numberreceiptentrycreation',
            name='cgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='numberreceiptentrycreation',
            name='igst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='numberreceiptentrycreation',
            name='sgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
