# Generated by Django 6.0.1 on 2026-07-22 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0007_alter_rchandover_vehicle_received'),
    ]

    operations = [
        # NOTE: the old cgst/sgst percent fields are intentionally NOT removed
        # here. Removing them in the same migration as adding the new amount
        # fields would drop their data before it could be backfilled into the
        # new fields (see 0009_backfill_rto_gst_amounts and
        # 0010_remove_old_gst_percent_fields, which do the backfill and then
        # the removal as separate, ordered steps).
        migrations.AddField(
            model_name='numberreceiptentrycreation',
            name='cgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='numberreceiptentrycreation',
            name='igst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='numberreceiptentrycreation',
            name='sgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
