# Generated by Django 6.0.1 on 2026-07-22 15:00
#
# Data migration: backfill cgst_amount/sgst_amount/igst_amount for rows that
# existed before 0008_replace_hardcoded_gst_with_split_gst introduced those
# fields (which default to 0). At this point in the migration graph the old
# cgst/sgst percent fields have NOT been removed yet (removal happens in
# 0010_remove_old_gst_percent_fields), so the values each historical document
# was actually charged at are still readable here. This intentionally
# replicates the OLD hardcoded pre-split_gst() formula
# (see rto/models.py NumberReceiptEntryCreation.save() before commit fdb3740):
#
#     cgst_amount = rate * cgst / 100
#     sgst_amount = rate * sgst / 100
#     igst_amount = 0  (IGST did not exist before split_gst() was introduced)
#
# using each row's OWN stored cgst/sgst percentage, not today's
# company-configured rate — the goal is to preserve what was actually charged
# on that historical document, not retroactively recompute it.
from decimal import Decimal

from django.db import migrations


def backfill_gst_amounts(apps, schema_editor):
    NumberReceiptEntryCreation = apps.get_model('rto', 'NumberReceiptEntryCreation')
    db_alias = schema_editor.connection.alias

    for entry in NumberReceiptEntryCreation.objects.using(db_alias).all():
        rate = entry.rate or Decimal('0')
        cgst_pct = entry.cgst or Decimal('0')
        sgst_pct = entry.sgst or Decimal('0')

        cgst_amount = (rate * cgst_pct / Decimal('100')).quantize(Decimal('0.01'))
        sgst_amount = (rate * sgst_pct / Decimal('100')).quantize(Decimal('0.01'))

        entry.cgst_amount = cgst_amount
        entry.sgst_amount = sgst_amount
        entry.igst_amount = Decimal('0.00')
        entry.save(update_fields=['cgst_amount', 'sgst_amount', 'igst_amount'])


def noop_reverse(apps, schema_editor):
    # Old cgst/sgst fields still hold their original values at this point in
    # the graph, so there's nothing to restore on reverse - just leave the
    # new amount fields as computed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0008_replace_hardcoded_gst_with_split_gst'),
    ]

    operations = [
        migrations.RunPython(backfill_gst_amounts, noop_reverse),
    ]
