# Generated by Django 6.0.1 on 2026-07-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0009_backfill_rto_gst_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberreceiptentrycreation',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='numberreceiptentrycreation',
            name='sgst',
        ),
    ]
