# Generated by Django 6.0.1 on 2026-07-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0010_remove_old_gst_percent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcbookissue',
            name='rc_book_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='rto.rcbookcreation'),
        ),
    ]
