# Generated by Django 6.0.1 on 2026-05-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeloan',
            name='first_emi_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeloan',
            name='sanctioned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
