# Generated by Django 6.0.5 on 2026-06-24 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_financeloan_hp_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-entry_date', '-created_at'], 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='company_gstin',
            field=models.CharField(blank=True, max_length=20, verbose_name='Company GSTIN'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_vehicle_purchase',
            field=models.BooleanField(default=False, verbose_name='Vehicle Purchase'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='multi_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='number_plate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reference_docname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reference_doctype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(db_index=True, max_length=200)),
                ('party_type', models.CharField(blank=True, max_length=100)),
                ('party', models.CharField(blank=True, max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.journalentry')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
