# Generated by Django 6.0.5 on 2026-06-24 19:01

from django.db import migrations


def forwards(apps, schema_editor):
    JournalEntry = apps.get_model('billing', 'JournalEntry')
    JournalEntryLine = apps.get_model('billing', 'JournalEntryLine')
    for entry in JournalEntry.objects.all():
        if not entry.account_name and not entry.amount:
            continue
        JournalEntryLine.objects.create(
            entry=entry,
            account=entry.account_name or 'Unspecified',
            debit=entry.amount if entry.entry_type == 'debit' else 0,
            credit=entry.amount if entry.entry_type == 'credit' else 0,
        )


def backwards(apps, schema_editor):
    # No-op: the legacy flat fields are dropped in the next migration, so
    # there's nothing meaningful to restore them from on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_journal_entry_lines_schema'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
