# Generated by Django 6.0.5 on 2026-06-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_journal_entry_lines_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='entry_type',
        ),
    ]
