# Generated by Django 6.0.7 on 2026-07-14 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_invoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
