# Generated by Django 6.0.1 on 2026-07-17 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_invoiceitem_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='source_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='billing.payment'),
        ),
    ]
