# Generated by Django 6.0.1 on 2026-05-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparesitem',
            name='item_group',
            field=models.CharField(blank=True, help_text='Item group classification (e.g. Engine, Electrical, Body)', max_length=100),
        ),
    ]
