# Generated by Django 6.0.1 on 2026-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_sparesissue_total_price_sparesissue_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='stock_quantity',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
