# Generated by Django 6.0.5 on 2026-06-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_sparesitem_item_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='get_customer_order',
            field=models.BooleanField(default=False, verbose_name='Get Customer Order'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='get_estimation',
            field=models.BooleanField(default=False, verbose_name='Get Estimation'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Average'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='one_month_qty',
            field=models.IntegerField(default=0, verbose_name='1 Month'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='ordered_qty',
            field=models.IntegerField(default=0, verbose_name='Ordered QTY'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='Stock QTY'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='used_qty',
            field=models.IntegerField(default=0, verbose_name='Used QTY'),
        ),
    ]
