# Generated by Django 6.0.5 on 2026-06-24 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0003_erp_alignment_po_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquote',
            name='total_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_type', models.CharField(choices=[('on_net_total', 'On Net Total'), ('on_previous_row_amount', 'On Previous Row Amount'), ('on_previous_row_total', 'On Previous Row Total'), ('actual', 'Actual')], default='on_net_total', max_length=30, verbose_name='Type')),
                ('account_head', models.CharField(max_length=200)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='spares.purchaseinvoice')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_type', models.CharField(choices=[('on_net_total', 'On Net Total'), ('on_previous_row_amount', 'On Previous Row Amount'), ('on_previous_row_total', 'On Previous Row Total'), ('actual', 'Actual')], default='on_net_total', max_length=30, verbose_name='Type')),
                ('account_head', models.CharField(max_length=200)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='spares.purchaseorder')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_type', models.CharField(choices=[('on_net_total', 'On Net Total'), ('on_previous_row_amount', 'On Previous Row Amount'), ('on_previous_row_total', 'On Previous Row Total'), ('actual', 'Actual')], default='on_net_total', max_length=30, verbose_name='Type')),
                ('account_head', models.CharField(max_length=200)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='spares.supplierquote')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
