# Generated by Django 6.0.5 on 2026-07-08 08:41
# Hand-edited: the auto-generated AlterField below would have silently corrupted
# the job_card column (CharField 'JC-2'/'114'/etc -> FK) since SQLite's loose
# typing doesn't error on a type mismatch. Replaced with a safe rename ->
# nullable-FK -> data-migrate -> drop-legacy -> not-null sequence that
# preserves the existing rows' job card linkage.

import django.db.models.deletion
from django.db import migrations, models


def migrate_job_card_to_fk(apps, schema_editor):
    SparesIssueAlteration = apps.get_model('spares', 'SparesIssueAlteration')
    JobCard = apps.get_model('service', 'JobCard')
    fallback = None
    for row in SparesIssueAlteration.objects.all():
        raw = (row.job_card_legacy or '').strip()
        jc = None
        if raw.isdigit():
            jc = JobCard.objects.filter(pk=int(raw)).first()
        if jc is None and raw.upper().startswith('JC-') and raw[3:].isdigit():
            jc = JobCard.objects.filter(pk=int(raw[3:])).first()
        if jc is None:
            if fallback is None:
                fallback = JobCard.objects.order_by('pk').first()
            jc = fallback
        row.job_card_id = jc.pk if jc else None
        row.save(update_fields=['job_card'])


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_labourwork'),
        ('service', '0007_jobcard_amended_from_jobcard_cancelled_at_and_more'),
        ('spares', '0004_tax_charge_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparesissuealteration',
            name='common_discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Common Discount'),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='indivitual',
            field=models.BooleanField(default=True, verbose_name='Individual Discount'),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spares_issue_alterations', to='masters.supplier'),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='party_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sparesissuealterationitem',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='sparesissuealterationitem',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='sparesissuealterationitem',
            name='uom',
            field=models.CharField(blank=True, default='Nos', max_length=20),
        ),
        migrations.RenameField(
            model_name='sparesissuealteration',
            old_name='job_card',
            new_name='job_card_legacy',
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='job_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spares_issue_alterations', to='service.jobcard'),
        ),
        migrations.RunPython(migrate_job_card_to_fk, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sparesissuealteration',
            name='job_card_legacy',
        ),
        migrations.AlterField(
            model_name='sparesissuealteration',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spares_issue_alterations', to='service.jobcard'),
        ),
    ]
