# Generated by Django 6.0.5 on 2026-07-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_jobcard_amended_from_jobcard_cancelled_at_and_more'),
        ('spares', '0005_sparesissuealteration_common_discount_and_more'),
        ('used_vehicles', '0002_usedvehiclejobcard_usedvehiclefinalinspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparesissuealteration',
            name='used_vehicle_job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spares_issue_alterations', to='used_vehicles.usedvehiclejobcard'),
        ),
        migrations.AlterField(
            model_name='sparesissuealteration',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spares_issue_alterations', to='service.jobcard'),
        ),
    ]
