# Generated by Django 6.0.5 on 2026-07-09 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_modulepermission_module'),
        ('masters', '0006_jobcardcomplaintmaster_and_more'),
        ('spares', '0007_requestsupplierquote_supplierquote_request_quotation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cash_account',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='has_tcs',
            field=models.BooleanField(default=False, verbose_name='Has TCS'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='pay_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('adjustment', 'Adjustment'), ('cash', 'Cash')], max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tcs_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='item_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='part_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Part No.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_order',
            field=models.ForeignKey(blank=True, help_text='Only meaningful when Get Customer Order is checked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='spares.countersale'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='load_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='delivery_need_qty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='part_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Part No.'),
        ),
        migrations.CreateModel(
            name='SparesPurchaseEstimationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('estimation_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('chasis_no', models.CharField(blank=True, help_text='Reference: Vehicle Chasis Number Master link; no Django master exists, kept as a snapshot label', max_length=100, verbose_name='Chasis No')),
                ('vehicle_code', models.CharField(blank=True, max_length=100)),
                ('vehicle_name', models.CharField(blank=True, max_length=200)),
                ('estimation_total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('balance_delivery_qty', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('labor_total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='spares.sparespurchaseestimationmaster')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('insurance_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spares_estimations', to='masters.supplier')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Spares Purchase Estimation Masters',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SparesPurchaseEstimationLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('labor_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.labourwork')),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_details', to='spares.sparespurchaseestimationmaster')),
            ],
            options={
                'verbose_name_plural': 'Spares Purchase Estimation Labor Charges',
            },
        ),
        migrations.CreateModel(
            name='SparesPurchaseEstimationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('confirm', models.BooleanField(default=False, verbose_name='Confirm To Order')),
                ('gst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('delivery_balance_qty', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spares.sparesitem')),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spares.sparespurchaseestimationmaster')),
            ],
            options={
                'verbose_name_plural': 'Spares Purchase Estimation Items',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='estimation',
            field=models.ForeignKey(blank=True, help_text='Only meaningful when Get Estimation is checked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='spares.sparespurchaseestimationmaster'),
        ),
    ]
