# Generated by Django 6.0.5 on 2026-07-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_invoice_actual_refund_amount_and_more'),
        ('masters', '0006_jobcardcomplaintmaster_and_more'),
        ('service', '0008_chasisdetailrow_complaintdetail_enginedetailrow_and_more'),
        ('spares', '0008_purchaseinvoice_cash_account_purchaseinvoice_has_tcs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='countersale',
            name='accounts_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='countersale',
            name='accounts_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='countersale',
            name='balance_delivery_qty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='countersale',
            name='bank_ref_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countersale',
            name='bank_ref_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='countersale',
            name='counter_sale_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='countersale',
            name='ledger_voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_sales', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='countersale',
            name='sale_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('order', 'Order')], default='sale', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='countersale',
            name='spot_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countersaleitem',
            name='delivery_balance_qty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='countersaleitem',
            name='issue_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countersaleitem',
            name='stock_qty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Snapshot of on-hand stock at issue time', max_digits=10),
        ),
        migrations.AddField(
            model_name='countersalereturn',
            name='accounts_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='countersalereturn',
            name='accounts_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='countersalereturn',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='countersalereturn',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount %', max_digits=5),
        ),
        migrations.AddField(
            model_name='countersalereturn',
            name='godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_sale_returns', to='masters.warehouse'),
        ),
        migrations.AddField(
            model_name='countersalereturn',
            name='gst_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='countersalereturnitem',
            name='delivery_balance_qty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='countersalereturnitem',
            name='issue_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countersalereturnitem',
            name='stock_qty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='engine_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='frame_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='model',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vehicle Model'),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='register_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='service_invoice_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='vehicle_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sparesissuealterationitem',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Returned'),
        ),
        migrations.AddField(
            model_name='sparesissuealterationitem',
            name='last_return_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sparesissuealterationitem',
            name='ref_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sparesissuealterationitem',
            name='stock_balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sparesissuealterationitem',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='ServiceSparesIssueReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('return_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('frame_no', models.CharField(blank=True, max_length=100)),
                ('register_no', models.CharField(blank=True, max_length=50)),
                ('party_name', models.CharField(blank=True, max_length=200)),
                ('spares_issue_date', models.DateField(blank=True, null=True)),
                ('total_qty', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('stock_return_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='spares.servicesparesissuereturn')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_spares_issue_returns', to='masters.warehouse')),
                ('job_card', models.ForeignKey(blank=True, help_text='New-vehicle snapshot link; for a used-vehicle issue, derive via spares_issue.target_job_card instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spares_issue_returns', to='service.jobcard')),
                ('spares_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='spares.sparesissuealteration')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Service Spares Issue Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSparesIssueReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('last_return_quantity', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('return_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('is_returned', models.BooleanField(default=True, verbose_name='Returned')),
                ('ref_quantity', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('stock_balance', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bin')),
                ('issue_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spares.servicesparesissuereturn')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spares.sparesitem')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.rack')),
            ],
            options={
                'verbose_name_plural': 'Service Spares Issue Return Items',
            },
        ),
        migrations.CreateModel(
            name='SparesIssueAlterationDeletedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('alteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_items', to='spares.sparesissuealteration')),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spares.sparesitem')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.rack')),
            ],
            options={
                'verbose_name_plural': 'Spares Issue Alteration Deleted Items',
            },
        ),
    ]
