# Generated by Django 6.0.5 on 2026-07-09 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_modulepermission_module'),
        ('masters', '0006_jobcardcomplaintmaster_and_more'),
        ('spares', '0009_countersale_accounts_from_countersale_accounts_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparesProfitPercentageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_mrp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('without_mrp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Spares Profit Percentage',
                'verbose_name_plural': 'Spares Profit Percentage',
            },
        ),
        migrations.CreateModel(
            name='SparesPurchaseQtyDaysSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_or_order_qty_days', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Spares Purchase Order Qty Days Settings',
                'verbose_name_plural': 'Spares Purchase Order Qty Days Settings',
            },
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='brand',
            field=models.CharField(choices=[('ss_bikes', 'SS Bikes'), ('euler', 'Euler')], default='ss_bikes', help_text="Collapses the reference's 'Euler Spares Issue Alteration' into this same model/table, tagged by brand", max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceSparesWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('warranty_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('claim_no', models.CharField(blank=True, max_length=100)),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('parts_dispatch_date', models.DateField(blank=True, null=True)),
                ('claim_received_date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('chasis_no', models.CharField(blank=True, max_length=100, verbose_name='Chasis No')),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('closed', 'Closed')], default='open', max_length=20)),
                ('vehicle_name', models.CharField(blank=True, max_length=200)),
                ('history', models.TextField(blank=True)),
                ('ndp_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('dispatch_on', models.DateField(blank=True, null=True)),
                ('dock_no', models.CharField(blank=True, max_length=50)),
                ('claim_register_in_pymidol', models.BooleanField(default=False)),
                ('generate_invoice_in_pymidol', models.BooleanField(default=False)),
                ('courier_parts', models.BooleanField(default=False)),
                ('courier_invoice_bill_on', models.DateField(blank=True, null=True)),
                ('claim_for', models.CharField(blank=True, max_length=200)),
                ('payment_received_date', models.DateField(blank=True, null=True)),
                ('brand', models.CharField(choices=[('ss_bikes', 'SS Bikes'), ('euler', 'Euler')], default='ss_bikes', help_text="Collapses the reference's 'Euler Service Spares Warranty' into this same model/table, tagged by brand", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='spares.servicespareswarranty')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_spares_warranties', to='accounts.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_spares_warranties', to='masters.supplier')),
            ],
            options={
                'verbose_name_plural': 'Service Spares Warranties',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSparesWarrantyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_warranty_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('ndp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spares.sparesitem')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spares.servicespareswarranty')),
            ],
            options={
                'verbose_name_plural': 'Service Spares Warranty Items',
            },
        ),
        migrations.CreateModel(
            name='SparesMRPPriceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('revision_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('price_list', models.CharField(choices=[('standard_selling', 'Standard Selling'), ('standard_buying', 'Standard Buying')], default='standard_selling', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='spares.sparesmrppricerevision')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Spares MRP Price Revisions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SparesMRPPriceRevisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Snapshot of the current price at save time', max_digits=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('updated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spares.sparesitem')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spares.sparesmrppricerevision')),
            ],
            options={
                'verbose_name_plural': 'Spares MRP Price Revision Items',
            },
        ),
        migrations.CreateModel(
            name='VehicleSparesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('purchase_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('mrp_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('spare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_spares_master', to='spares.sparesitem')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Spares Masters',
                'ordering': ['spare__item_name'],
            },
        ),
    ]
