# Generated by Django 6.0.5 on 2026-07-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0010_sparesprofitpercentagesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countersalereturnitem',
            name='return_qty',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text="Quantity actually returned, distinct from the original sale quantity -- confirmed live as the reference's own separate return_qty field", max_digits=10),
        ),
        migrations.AlterField(
            model_name='countersalereturnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text="Original sale quantity -- matches the reference's own qty field", max_digits=10),
        ),
    ]
