# Generated by Django 6.0.1 on 2026-07-16 19:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0013_alter_purchaseorderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countersale',
            name='stock_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countersale',
            name='stock_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countersalereturn',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='countersalereturn',
            name='stock_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countersalereturn',
            name='stock_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='spares.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='stock_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparesissuealteration',
            name='stock_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockcountupdate',
            name='stock_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='stock_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='stock_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='one_month_qty',
            field=models.IntegerField(blank=True, default=0, verbose_name='1 Month'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='ordered_qty',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ordered QTY'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='stock_qty',
            field=models.IntegerField(blank=True, default=0, verbose_name='Stock QTY'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='used_qty',
            field=models.IntegerField(blank=True, default=0, verbose_name='Used QTY'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
