# Generated by Django 6.0.1 on 2026-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0015_backfill_counter_sale_return_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
