# Generated by Django 6.0.1 on 2026-07-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0016_add_purchase_invoice_item_igst'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='total_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
