# Generated by Django 6.0.1 on 2026-05-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_group',
            field=models.CharField(blank=True, help_text='Supplier group e.g. OEM, Local, Distributor', max_length=100),
        ),
    ]
