# Generated by Django 6.0.5 on 2026-06-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_supplier_supplier_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_prepaid_supplier',
            field=models.BooleanField(default=False, verbose_name='Is Prepaid Supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_transporter',
            field=models.BooleanField(default=False, verbose_name='Is Transporter'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_limit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Supplier Limit Amount'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual'), ('partnership', 'Partnership')], default='company', max_length=20),
        ),
    ]
