# Generated by Django 6.0.5 on 2026-07-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_bunkname_financecompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('standard_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Labour Work Catalog',
                'ordering': ['name'],
            },
        ),
    ]
