# Generated by Django 6.0.5 on 2026-07-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_labourwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobcardComplaintMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200, unique=True, verbose_name='Complaint')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Jobcard Complaint Master',
                'ordering': ['name_text'],
            },
        ),
        migrations.CreateModel(
            name='JobcardSupervisorObservationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200, unique=True, verbose_name='Observation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Jobcard Supervisor Observation Master',
                'ordering': ['name_text'],
            },
        ),
    ]
