# Generated by Django 6.0.5 on 2026-07-09 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_modulepermission_module'),
        ('masters', '0006_jobcardcomplaintmaster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFormSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('order_form_no', models.CharField(max_length=50, unique=True)),
                ('order_form_count', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('', '—'), ('used', 'Used'), ('unused', 'Unused')], max_length=20)),
                ('allotment', models.CharField(blank=True, max_length=100)),
                ('sales_order_id', models.CharField(blank=True, max_length=100)),
                ('sales_order_status', models.CharField(blank=True, max_length=100)),
                ('rto_status', models.CharField(blank=True, default='available', max_length=50)),
                ('f20_status', models.CharField(blank=True, default='not done', max_length=50)),
                ('ex_change_vehicle_status', models.IntegerField(blank=True, default=0)),
                ('series_type', models.CharField(blank=True, choices=[('new_vehicle', 'New Vehicle'), ('used_vehicle', 'Used Vehicle')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='masters.orderformseries')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_form_series', to='accounts.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order Form Series',
                'ordering': ['-order_form_no'],
            },
        ),
        migrations.CreateModel(
            name='OrderFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_vehicle', models.BooleanField(default=False)),
                ('used_vehicle', models.BooleanField(default=False)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('digits', models.IntegerField(blank=True, default=5)),
                ('from_no', models.IntegerField(blank=True, default=0)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('to_no', models.IntegerField(blank=True, default=0, help_text='Computed: from_no + count - 1')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch')),
            ],
            options={
                'verbose_name': 'Order Form Settings',
                'verbose_name_plural': 'Order Form Settings',
            },
        ),
    ]
