# Generated by Django 6.0.5 on 2026-07-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_modulepermission_module'),
        ('customers', '0003_customer_gst_category'),
        ('masters', '0007_orderformseries_orderformsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('disable', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=200, verbose_name='Vehicle Name')),
                ('sub_group', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_prices', to='accounts.branch')),
                ('model_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_prices', to='customers.bikemodel', verbose_name='Vehicle Code')),
            ],
            options={
                'verbose_name_plural': 'Customer Price List',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(max_length=100, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.customerprice')),
            ],
            options={
                'verbose_name_plural': 'Customer Price Items',
            },
        ),
        migrations.CreateModel(
            name='DealerPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=200, verbose_name='Model Name')),
                ('sub_group', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealer_price_lists', to='customers.customer')),
                ('model_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_price_lists', to='customers.bikemodel', verbose_name='Model Code')),
            ],
            options={
                'verbose_name_plural': 'Dealer Price Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(max_length=100, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.dealerpricelist')),
            ],
            options={
                'verbose_name_plural': 'Dealer Price Items',
            },
        ),
        migrations.CreateModel(
            name='ModelAndPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=200, verbose_name='Vehicle Name')),
                ('sub_group', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('color_code', models.CharField(blank=True, max_length=20)),
                ('percentage', models.IntegerField(blank=True, default=0)),
                ('ex_show_room', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Ex Showroom')),
                ('pdi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='PDI')),
                ('rsa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='RSA')),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('updated_insurance_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Updated Insurance Rate')),
                ('amc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='AMC')),
                ('warranty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Protection Plus')),
                ('charge_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Charge 1')),
                ('charge_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Charge 2')),
                ('charge_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Charge 3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_records', to='customers.bikemodel', verbose_name='Vehicle Code')),
            ],
            options={
                'verbose_name_plural': 'Model and Price',
                'ordering': ['-created_at'],
            },
        ),
    ]
