# Generated by Django 6.0.5 on 2026-07-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_modulepermission_module'),
        ('customers', '0004_vehiclemastersettings_vehiclemastersettingsitem'),
        ('masters', '0008_customerprice_customerpriceitem_dealerpricelist_and_more'),
        ('spares', '0010_sparesprofitpercentagesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFittingSpares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_fitting_spares', to='accounts.branch')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitting_spares', to='customers.bikemodel', verbose_name='Vehicle Name')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Fitting Spares',
                'ordering': ['vehicle'],
            },
        ),
        migrations.CreateModel(
            name='VehicleFittingSpareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('gst', models.CharField(blank=True, help_text='Reference types this field as free text (Data), not a rate -- preserved as-is', max_length=20)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spares.sparesitem')),
                ('fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.vehiclefittingspares')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Fitting Spare Items',
            },
        ),
    ]
