# Generated by Django 6.0.5 on 2026-07-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_vehiclefittingspares_vehiclefittingspareitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NormalHelmetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled', models.BooleanField(default=False)),
                ('helmet_code', models.CharField(max_length=50, unique=True)),
                ('helmet_name', models.CharField(max_length=200)),
                ('uom', models.CharField(default='Nos', max_length=20)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('gst_percent', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Reference links to an Item Tax Template; no such model exists in Django -- a plain percent field instead', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helmets', to='masters.vehicletype')),
            ],
            options={
                'verbose_name_plural': 'Normal Helmet Masters',
                'ordering': ['helmet_name'],
            },
        ),
    ]
