# Generated by Django 6.0.1 on 2026-07-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_vehicletype_normalhelmetmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_currency',
            field=models.CharField(blank=True, default='INR', max_length=10, verbose_name='Default Currency'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax ID / PAN'),
        ),
    ]
