# Generated by Django 6.0.5 on 2026-05-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='free_services_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='total_free_services',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
