# Generated by Django 6.0.5 on 2026-06-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('sales', 'Sales'), ('customers', 'Customers'), ('finance', 'Finance / Billing'), ('rto', 'RTO'), ('service', 'Service'), ('spares', 'Spares'), ('vas', 'Value Added Services'), ('vehicle_master', 'Vehicle Master'), ('masters', 'Masters'), ('reports', 'Reports'), ('admin', 'Admin')], max_length=30)),
                ('can_view', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name_plural': 'Module Permissions',
                'ordering': ['role__role_name', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
