# Generated by Django 6.0.5 on 2026-06-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_modulepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermission',
            name='can_create',
            field=models.BooleanField(default=True, verbose_name='Create'),
        ),
        migrations.AddField(
            model_name='modulepermission',
            name='can_delete',
            field=models.BooleanField(default=True, verbose_name='Delete'),
        ),
        migrations.AddField(
            model_name='modulepermission',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Edit'),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
    ]
