# Generated by Django 6.0.5 on 2026-07-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_module_permission_crud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('sales', 'Sales'), ('customers', 'Customers'), ('finance', 'Finance / Billing'), ('rto', 'RTO'), ('service', 'Service'), ('spares', 'Spares'), ('vas', 'Value Added Services'), ('vehicle_master', 'Vehicle Master'), ('masters', 'Masters'), ('used_vehicles', 'Used Vehicles'), ('reports', 'Reports'), ('admin', 'Admin')], max_length=30),
        ),
    ]
