# Generated by Django 6.0.5 on 2026-07-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_modulepermission_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPercentageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_charge_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('out_work_return_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('spares_issue_alteration_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Discount Percentage Master',
                'verbose_name_plural': 'Discount Percentage Master',
            },
        ),
        migrations.CreateModel(
            name='LedgerCreationDateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_days', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ledger Creation Date Master',
                'verbose_name_plural': 'Ledger Creation Date Master',
            },
        ),
    ]
