# Generated by Django 6.0.7 on 2026-07-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_reset_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
