# Generated by Django 6.0.1 on 2026-07-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_last_password_reset_request_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
    ]
