# Generated by Django 6.0.7 on 2026-07-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_companysettings_igst_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='igst_rate',
        ),
    ]
