# Generated by Django 6.0.1 on 2026-07-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_companysettings_igst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='allow_without_enquiry_form',
            field=models.BooleanField(default=True, help_text='If unchecked, a Sales Order at this branch must be linked to a Sales Enquiry.', verbose_name='Allow Sales Order without Enquiry Form'),
        ),
    ]
