# Generated by Django 6.0.1 on 2026-07-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_branch_allow_without_enquiry_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='gl_backdating_days',
            field=models.PositiveIntegerField(default=90, help_text='Manual Journal Entry dates cannot be older than this many days.', verbose_name='GL Backdating Window (days)'),
        ),
    ]
