# Generated by Django 6.0.5 on 2026-05-22 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_fuelexpense'),
        ('customer_vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('service_type', models.CharField(blank=True, choices=[('free_service', 'Free Service'), ('paid_service', 'Paid Service'), ('accidental', 'Accidental Repair'), ('general', 'General')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Appointments',
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Bays',
                'ordering': ['bay_name'],
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_reading', models.IntegerField(blank=True, null=True)),
                ('problem_description', models.TextField(blank=True, null=True)),
                ('service_status', models.CharField(choices=[('pending', 'Pending'), ('water_wash', 'Water Wash'), ('in_bay', 'In Bay'), ('in_progress', 'In Progress'), ('outwork', 'Outwork'), ('final_inspection', 'Final Inspection'), ('ready', 'Ready'), ('invoiced', 'Invoiced')], db_index=True, default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='accounts.branch')),
                ('customer_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='customer_vehicles.customervehicle')),
                ('floor_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards_as_supervisor', to=settings.AUTH_USER_MODEL)),
                ('service_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards_as_advisor', to=settings.AUTH_USER_MODEL)),
                ('service_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='service.serviceappointment')),
            ],
            options={
                'verbose_name_plural': 'Job Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaborCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_charges', to='service.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Labor Charges',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='OutworkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('work_description', models.TextField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned')], default='issued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outwork_entries', to='service.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Outwork Entries',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='BayAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('assignment_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bay_assignments', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bay_assignments', to='service.jobcard')),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='service.servicebay')),
            ],
            options={
                'verbose_name_plural': 'Bay Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_enquiries_created', to=settings.AUTH_USER_MODEL)),
                ('customer_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_enquiries', to='customer_vehicles.customervehicle')),
            ],
            options={
                'verbose_name_plural': 'Service Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='service_enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service.serviceenquiry'),
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('labor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spares_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outwork_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='service_invoice', to='service.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Service Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
