# Generated by Django 6.0.5 on 2026-05-25 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDiscountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Discount Master',
                'ordering': ['service_type'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(max_length=200)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('estimation_date', models.DateField(auto_now_add=True)),
                ('labour_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spares_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Insurance'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_estimations', to='service.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Insurance Estimations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(blank=True, max_length=100)),
                ('claim_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled')], default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='service.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Warranty Claims',
                'ordering': ['-created_at'],
            },
        ),
    ]
