# Generated by Django 6.0.5 on 2026-05-25 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_vehicles', '0002_customervehicle_free_services_used_and_more'),
        ('service', '0002_servicediscountmaster_insuranceestimation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalWorkApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of additional work needed')),
                ('estimated_labour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_spares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('sent', 'Sent to Customer'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_approvals', to='service.jobcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('callback', 'Callback Later'), ('no_answer', 'No Answer'), ('booked', 'Appointment Booked')], max_length=20)),
                ('next_call_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='customer_vehicles.customervehicle')),
            ],
            options={
                'ordering': ['-call_date'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=100)),
                ('insurance_company', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=100)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled')], default='submitted', max_length=20)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insurance_estimation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.insuranceestimation')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='service.jobcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCardRevisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_service_km', models.IntegerField(help_text='Odometer reading for next service')),
                ('next_service_days', models.IntegerField(help_text='Days until next service')),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revisit', to='service.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardServiceChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_childs', to='service.jobcard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
