# Generated by Django 6.0.1 on 2026-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_outworkentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='service_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('water_wash', 'Water Wash'), ('in_bay', 'In Bay'), ('in_progress', 'In Progress'), ('outwork', 'Outwork'), ('final_inspection', 'Final Inspection'), ('ready', 'Ready'), ('invoiced', 'Invoiced')], db_index=True, default='pending', max_length=30),
        ),
    ]
