# Generated by Django 6.0.1 on 2026-06-04 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_vehicles', '0002_customervehicle_free_services_used_and_more'),
        ('service', '0003_additionalworkapproval_customercall_insuranceclaim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_type', models.CharField(choices=[('free_service', 'Free Service Due'), ('paid_service', 'Paid Service Due'), ('insurance_expiry', 'Insurance Expiry'), ('amc_renewal', 'AMC Renewal'), ('warranty_expiry', 'Warranty Expiry')], max_length=50)),
                ('due_km', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Call'), ('called', 'Called'), ('booked', 'Appointment Booked'), ('not_interested', 'Not Interested'), ('no_answer', 'No Answer')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reminders', to=settings.AUTH_USER_MODEL)),
                ('customer_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reminders', to='customer_vehicles.customervehicle')),
            ],
            options={
                'ordering': ['reminder_date'],
            },
        ),
    ]
