# Generated by Django 6.0.1 on 2026-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_jobcard_service_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceinvoice',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Service Invoices'},
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='labor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='outwork_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='spares_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceinvoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceinvoice',
            name='invoice_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
