# Generated by Django 6.0.5 on 2026-06-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicereminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='chassis_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Chassis No'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='is_cancelled_postponed',
            field=models.BooleanField(default=False, verbose_name='Appointment Cancel/Postponed'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='vehicle_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='whatsapp_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
