# Generated by Django 6.0.5 on 2026-06-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_bikemodel_dealer_cost_price'),
        ('service', '0005_serviceappointment_chassis_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Vehicle Code')),
                ('bike_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_master', to='customers.bikemodel', verbose_name='Vehicle / Bike Model')),
            ],
            options={
                'verbose_name': 'Vehicle Service Master',
            },
        ),
        migrations.CreateModel(
            name='VehicleServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Free Service 1', 'Free Service 1'), ('Free Service 2', 'Free Service 2'), ('Free Service 3', 'Free Service 3'), ('Paid Service', 'Paid Service'), ('General Checkup', 'General Checkup')], max_length=100, verbose_name='Service Type')),
                ('days_from_purchase', models.IntegerField(verbose_name='Service Days from Purchase')),
                ('km_from_purchase', models.IntegerField(verbose_name='Service KM from Purchase')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='service.vehicleservicemaster')),
            ],
            options={
                'verbose_name': 'Service Schedule',
                'ordering': ['days_from_purchase'],
            },
        ),
    ]
