# Generated by Django 6.0.5 on 2026-07-08 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_gst_category'),
        ('masters', '0005_labourwork'),
        ('service', '0006_erp_alignment_vehicle_service_master'),
        ('spares', '0004_tax_charge_lines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='service.jobcard'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='docstatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BayInCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_code', models.CharField(blank=True, max_length=100)),
                ('register_no', models.CharField(blank=True, max_length=50)),
                ('date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='service.bayincreation')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bay_in_entries', to='service.jobcard')),
                ('mechanic', models.ForeignKey(blank=True, help_text='Filtered to supplier_group=Labor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bay_in_entries', to='masters.supplier')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bay In Creation',
                'verbose_name_plural': 'Bay In Creations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BayOutCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_code', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='service.bayoutcreation')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bay_out_entries', to='service.jobcard')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bay_out_entries', to='masters.supplier')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bay Out Creation',
                'verbose_name_plural': 'Bay Out Creations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rework', models.BooleanField(default=False)),
                ('vehicle_name', models.CharField(blank=True, max_length=200)),
                ('chasis_number', models.CharField(blank=True, max_length=100)),
                ('mechanic_name', models.CharField(blank=True, max_length=200)),
                ('register_number', models.CharField(blank=True, max_length=50)),
                ('final_inspection_remarks', models.TextField()),
                ('revisit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='service.finalinspection')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_inspections', to='service.jobcard')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Final Inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaborChargesAlteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='service.laborchargesalteration')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_alterations', to='service.jobcard')),
                ('labours_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_alterations', to='masters.supplier', verbose_name='Labour Name (Spares Used Mechanic)')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Labor Charges Alterations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaborDetailLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('alteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_details', to='service.laborchargesalteration')),
                ('labor_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.labourwork', verbose_name='Labor Work')),
            ],
            options={
                'verbose_name_plural': 'Labor Detail Lines',
            },
        ),
        migrations.CreateModel(
            name='LaborSpareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('alteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spares_used', to='service.laborchargesalteration')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spares.sparesitem')),
            ],
            options={
                'verbose_name_plural': 'Labor Spare Items',
            },
        ),
        migrations.CreateModel(
            name='OutworkEntryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('gate_pass', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='service.outworkentryissue')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outwork_issues', to='masters.warehouse')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outwork_issues', to='service.jobcard')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outwork_issues', to='masters.supplier')),
            ],
            options={
                'verbose_name_plural': 'Outwork Entry Issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutworkEntryReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rework', models.BooleanField(default=False)),
                ('payment_type', models.CharField(blank=True, choices=[('adjustment', 'Adjustment'), ('cash', 'Cash')], max_length=20)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor_spares_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('pending_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='service.outworkentryreturn')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outwork_returns', to='service.jobcard')),
                ('outwork_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='service.outworkentryissue')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outwork_returns', to='masters.supplier')),
            ],
            options={
                'verbose_name_plural': 'Outwork Entry Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutworkReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('outwork_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outwork_details', to='service.outworkentryreturn')),
            ],
            options={
                'verbose_name_plural': 'Outwork Return Details',
            },
        ),
        migrations.CreateModel(
            name='OutworkReturnSpareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spares.sparesitem')),
                ('outwork_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_work_issue_spares_list', to='service.outworkentryreturn')),
            ],
            options={
                'verbose_name_plural': 'Outwork Return Spare Items',
            },
        ),
        migrations.CreateModel(
            name='OutworkSpareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=9, max_digits=5)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spares.sparesitem')),
                ('outwork_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outwork_spares', to='service.outworkentryissue')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.rack')),
            ],
            options={
                'verbose_name_plural': 'Outwork Spare Items',
            },
        ),
        migrations.CreateModel(
            name='OutworkWorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Tax (%)')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('work_type', models.CharField(blank=True, max_length=100)),
                ('outwork_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_details', to='service.outworkentryissue')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'Outwork Work Details',
            },
        ),
        migrations.CreateModel(
            name='WaterWashDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('register_number', models.CharField(blank=True, max_length=50)),
                ('vehicle_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='service.waterwashdone')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='water_wash_entries', to='service.jobcard')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Water Wash Done',
                'ordering': ['-created_at'],
            },
        ),
    ]
