# Generated by Django 6.0.5 on 2026-07-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_jobcardcomplaintmaster_and_more'),
        ('service', '0007_jobcard_amended_from_jobcard_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChasisDetailRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('yes_no', 'Yes/No'), ('good_bad_na', 'Good/Bad/NA'), ('ok_hi_low', 'OK/High/Low')], default='yes_no', max_length=20)),
                ('items', models.CharField(blank=True, max_length=200)),
                ('yes', models.BooleanField(default=False)),
                ('no', models.BooleanField(default=False)),
                ('ok', models.BooleanField(default=False)),
                ('high', models.BooleanField(default=False)),
                ('low', models.BooleanField(default=False)),
                ('good', models.BooleanField(default=False)),
                ('bad', models.BooleanField(default=False)),
                ('na', models.BooleanField(default=False)),
                ('yes_status', models.IntegerField(blank=True, default=0)),
                ('no_status', models.IntegerField(blank=True, default=0)),
                ('good_status', models.IntegerField(blank=True, default=0)),
                ('bad_status', models.IntegerField(blank=True, default=0)),
                ('na_status', models.IntegerField(blank=True, default=0)),
                ('ok_status', models.IntegerField(blank=True, default=0)),
                ('high_status', models.BooleanField(default=False)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chasis_details', to='service.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Chasis Detail Rows',
            },
        ),
        migrations.CreateModel(
            name='ComplaintDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('complaint_check_box', models.BooleanField(default=False)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('customer_complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.jobcardcomplaintmaster')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_details', to='service.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Complaint Details',
            },
        ),
        migrations.CreateModel(
            name='EngineDetailRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('yes_no', 'Yes/No'), ('ok_hi_low', 'OK/High/Low')], default='yes_no', max_length=20)),
                ('items', models.CharField(blank=True, max_length=200)),
                ('yes', models.BooleanField(default=False)),
                ('no', models.BooleanField(default=False)),
                ('ok', models.BooleanField(default=False)),
                ('high', models.BooleanField(default=False)),
                ('low', models.BooleanField(default=False)),
                ('area_mention', models.CharField(blank=True, max_length=200)),
                ('yes_status', models.CharField(blank=True, max_length=50)),
                ('no_status', models.CharField(blank=True, max_length=50)),
                ('ok_status', models.CharField(blank=True, max_length=50)),
                ('high_status', models.CharField(blank=True, max_length=50)),
                ('low_status', models.CharField(blank=True, max_length=50)),
                ('mention_status', models.CharField(blank=True, max_length=50)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_details', to='service.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Engine Detail Rows',
            },
        ),
        migrations.CreateModel(
            name='JobCardSupervisorObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('complaint_check_box', models.BooleanField(default=False)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.jobcardsupervisorobservationmaster')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_observations', to='service.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Job Card Supervisor Observations',
            },
        ),
        migrations.CreateModel(
            name='LightDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=200)),
                ('yes', models.BooleanField(default=False)),
                ('no', models.BooleanField(default=False)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_details', to='service.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Light Details',
            },
        ),
    ]
