# Generated by Django 6.0.5 on 2026-07-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_chasisdetailrow_complaintdetail_enginedetailrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outworkentryreturn',
            name='issue_spares_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Snapshot of the linked Outwork Entry Issue spares total, auto-set on save', max_digits=10),
        ),
        migrations.AddField(
            model_name='outworkentryreturn',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='issue_spares_amount + actual_amount + billing_amount, matching the reference formula', max_digits=10),
        ),
    ]
