# Generated by Django 6.0.5 on 2026-07-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_outworkentryreturn_issue_spares_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='claim_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
