# Generated by Django 6.0.7 on 2026-07-14 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_warrantyclaim_claim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicediscountmaster',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
