# Generated by Django 6.0.7 on 2026-07-16 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_servicediscountmaster_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborcharge',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
