# Generated by Django 6.0.5 on 2026-05-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amc_packages', to='customer_vehicles.customervehicle')),
            ],
            options={
                'verbose_name_plural': 'AMC Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionPlusPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protection_plus_packages', to='customer_vehicles.customervehicle')),
            ],
            options={
                'verbose_name_plural': 'Protection Plus Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSAPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rsa_packages', to='customer_vehicles.customervehicle')),
            ],
            options={
                'verbose_name_plural': 'RSA Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
