# Generated by Django 6.0.5 on 2026-07-08 19:18

import re

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _slug_code(name):
    code = re.sub(r'[^A-Za-z0-9]+', '-', name).strip('-').upper()[:40]
    return code or 'TYPE'


def populate_vas_types_from_legacy_labels(apps, schema_editor):
    """Data-preserving step: the old free-text package_name/provider_name
    fields are about to be removed in favor of amc_type/rsa_type/warranty_type
    FKs -- create (or reuse) a type master per distinct legacy label so no
    existing package's identifying label is silently dropped, mirroring the
    Phase 2 job_card CharField->FK migration's approach."""
    AMCPackage             = apps.get_model('vas', 'AMCPackage')
    RSAPackage             = apps.get_model('vas', 'RSAPackage')
    ProtectionPlusPackage  = apps.get_model('vas', 'ProtectionPlusPackage')
    AMCType                = apps.get_model('vas', 'AMCType')
    RSAType                = apps.get_model('vas', 'RSAType')
    WarrantyType           = apps.get_model('vas', 'WarrantyType')

    def get_or_create_type(model, name):
        name = (name or '').strip() or 'Unspecified'
        existing = model.objects.filter(name=name).first()
        if existing:
            return existing
        base_code = _slug_code(name)
        code = base_code
        suffix = 1
        while model.objects.filter(code=code).exists():
            suffix += 1
            code = f'{base_code}-{suffix}'
        return model.objects.create(code=code, name=name)

    for pkg in AMCPackage.objects.all():
        pkg.amc_type = get_or_create_type(AMCType, pkg.package_name)
        pkg.save(update_fields=['amc_type'])

    for pkg in RSAPackage.objects.all():
        pkg.rsa_type = get_or_create_type(RSAType, pkg.provider_name)
        pkg.save(update_fields=['rsa_type'])

    for pkg in ProtectionPlusPackage.objects.all():
        label = pkg.package_name or pkg.provider_name
        pkg.warranty_type = get_or_create_type(WarrantyType, label)
        pkg.save(update_fields=['warranty_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_modulepermission_module'),
        ('billing', '0010_alter_invoice_actual_refund_amount_and_more'),
        ('masters', '0006_jobcardcomplaintmaster_and_more'),
        ('sales', '0015_alter_additionalvehiclefitting_quantity_and_more'),
        ('vas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('amc_validity_days', models.IntegerField(blank=True, default=0)),
                ('amc_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('ss_bikes', models.BooleanField(default=True, verbose_name='SS Bikes')),
                ('yamaha', models.BooleanField(default=False)),
                ('deactivate_amc', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, help_text='Reference: Vehicle Type link; no Django master exists for this yet, kept as a snapshot label', max_length=100)),
                ('no_of_service', models.IntegerField(blank=True, default=0)),
                ('water_wash_count_free', models.IntegerField(blank=True, default=0)),
                ('service_interval_days', models.IntegerField(blank=True, default=0)),
                ('grace_days', models.IntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AMC Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RSAType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('rsa_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'RSA Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Warranty Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='vas.amcpackage'),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='chasis_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='docstatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='grace_days',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_packages', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='no_of_service',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_packages', to='sales.vehiclesalesorder'),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='service_interval',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='ss_bikes',
            field=models.BooleanField(default=True, verbose_name='SS Bikes'),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='vehicle_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='water_wash_count_free',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='without_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='yamaha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='vas.protectionpluspackage'),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='docstatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protection_plus_packages', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protection_plus_packages', to='sales.vehiclesalesorder'),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='without_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='vas.rsapackage'),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='docstatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsa_packages', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='rsa_portal_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='RSA Portal No'),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsa_packages', to='sales.vehiclesalesorder'),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='without_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='amcpackage',
            name='amc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='vas.amctype'),
        ),
        migrations.CreateModel(
            name='RSACreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rsa_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='vas.rsacreation')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rsa_creations', to='masters.supplier')),
                ('rsa_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rsa_creations', to='vas.rsatype')),
            ],
            options={
                'verbose_name_plural': 'RSA Creations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='rsa_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='vas.rsatype'),
        ),
        migrations.CreateModel(
            name='VASStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amc_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='vas.amctype')),
                ('rsa_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='vas.rsatype')),
                ('warranty_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='vas.warrantytype')),
            ],
            options={
                'verbose_name_plural': 'VAS Stock Ledgers',
            },
        ),
        migrations.CreateModel(
            name='VASSupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('invoice_date', models.DateField()),
                ('payment_type', models.CharField(blank=True, choices=[('adjustment', 'Adjustment'), ('cash', 'Cash')], max_length=20)),
                ('pay_mode', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('expected_date', models.DateField(blank=True, help_text='RSA invoices only', null=True)),
                ('cash_account', models.CharField(blank=True, help_text='RSA invoices only', max_length=200)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('pending_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='vas.vassupplierinvoice')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vas_invoices', to='accounts.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vas_invoices', to='masters.supplier')),
            ],
            options={
                'verbose_name_plural': 'VAS Supplier Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VASSupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('amc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vas.amctype')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vas.vassupplierinvoice')),
                ('rsa_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vas.rsatype')),
                ('warranty_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vas.warrantytype')),
            ],
            options={
                'verbose_name_plural': 'VAS Supplier Invoice Items',
            },
        ),
        migrations.CreateModel(
            name='VASStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment')], default='purchase', max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for purchase/adjustment-in, negative for sale/adjustment-out')),
                ('updated_quantity', models.IntegerField(blank=True, help_text='Running balance after this movement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vas_stock_movements', to='accounts.branch')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='vas.vasstockledger')),
                ('source_amc_package', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement', to='vas.amcpackage')),
                ('source_pp_package', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement', to='vas.protectionpluspackage')),
                ('source_rsa_package', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement', to='vas.rsapackage')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vas_stock_movements', to='masters.supplier')),
                ('source_invoice_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement', to='vas.vassupplierinvoiceitem')),
            ],
            options={
                'verbose_name_plural': 'VAS Stock Movements',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='warranty_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='vas.warrantytype'),
        ),
        migrations.RunPython(populate_vas_types_from_legacy_labels, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='amcpackage',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='protectionpluspackage',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='protectionpluspackage',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='rsapackage',
            name='provider_name',
        ),
    ]
