# Generated by Django 6.0.1 on 2026-07-16 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vas', '0002_amctype_rsatype_warrantytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vasstockmovement',
            name='reverses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='vas.vasstockmovement'),
        ),
    ]
