# Generated by Django 6.0.1 on 2026-07-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_branch_allow_without_enquiry_form'),
        ('vas', '0003_vasstockmovement_reverses'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcpackage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_packages', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='protectionpluspackage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protection_plus_packages', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='rsapackage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsa_packages', to='accounts.branch'),
        ),
    ]
