# Generated by Django 6.0.5 on 2026-05-17 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=50)),
                ('available_colors', models.TextField(blank=True, null=True)),
                ('ex_showroom_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bike Models',
                'ordering': ['brand', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhaar_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('chassis_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20)),
                ('warehouse_location', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='customers.bikemodel')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_stock', to='accounts.branch')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
