# Generated by Django 6.0.1 on 2026-06-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='dealer_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dealer purchase price from manufacturer (used for profit calculations)', max_digits=10, null=True),
        ),
    ]
