# Generated by Django 6.0.5 on 2026-07-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_bikemodel_dealer_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gst_category',
            field=models.CharField(choices=[('Registered Regular', 'Registered Regular'), ('Registered Composition', 'Registered Composition'), ('Unregistered', 'Unregistered'), ('SEZ', 'SEZ'), ('Overseas', 'Overseas'), ('Deemed Export', 'Deemed Export'), ('UIN Holders', 'UIN Holders'), ('Tax Deductor', 'Tax Deductor'), ('Tax Collector', 'Tax Collector'), ('Input Service Distributor', 'Input Service Distributor')], default='Unregistered', max_length=30),
        ),
    ]
