# Generated by Django 6.0.5 on 2026-07-09 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_gst_category'),
        ('sales', '0016_vehiclesalesorder_order_form_series'),
        ('service', '0008_chasisdetailrow_complaintdetail_enginedetailrow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMasterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('master_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('has_exchange_vehicle', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='customers.vehiclemastersettings')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exchange_vehicle_id', models.ForeignKey(blank=True, help_text='Reference Link target is a standalone Exchange Vehicle Master; Django has no such freestanding master -- this points directly at sales.ExchangeVehicle, which is normally reached via its owning VehicleSalesOrder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.exchangevehicle')),
                ('service_settings', models.ForeignKey(blank=True, help_text='Reuses the existing service.VehicleServiceMaster (built in an earlier round) rather than duplicating it under masters -- same OneToOneField(BikeModel) shape the reference doctype implies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.vehicleservicemaster')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_settings', to='customers.bikemodel')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Master Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMasterSettingsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('chasis_no', models.CharField(max_length=100, verbose_name='Chasis No')),
                ('code', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='No Product Color master exists in Django -- free text, matching the existing VehicleStock.color precedent', max_length=50)),
                ('book_no', models.CharField(max_length=100, verbose_name='Book No')),
                ('color_code', models.CharField(blank=True, max_length=20)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.vehiclemastersettings')),
                ('vehicle_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.bikemodel')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Master Settings Items',
            },
        ),
    ]
