# Generated by Django 6.0.1 on 2026-07-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_vehiclemastersettings_vehiclemastersettingsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
