# Generated by Django 6.0.5 on 2026-07-08 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_vehicles', '0002_usedvehiclejobcard_usedvehiclefinalinspection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='service_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_vehicle_job_cards_as_advisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedvehiclesale',
            name='sales_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_vehicle_sales_handled', to=settings.AUTH_USER_MODEL),
        ),
    ]
