# Generated by Django 6.0.5 on 2026-07-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_jobcardcomplaintmaster_and_more'),
        ('used_vehicles', '0003_usedvehiclejobcard_service_advisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedVehicleChasisDetailRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=200)),
                ('yes', models.BooleanField(default=False)),
                ('no', models.BooleanField(default=False)),
                ('ok', models.BooleanField(default=False)),
                ('high', models.BooleanField(default=False)),
                ('low', models.BooleanField(default=False)),
                ('good', models.BooleanField(default=False)),
                ('bad', models.BooleanField(default=False)),
                ('na', models.BooleanField(default=False)),
                ('yes_status', models.IntegerField(blank=True, default=0)),
                ('no_status', models.IntegerField(blank=True, default=0)),
                ('good_status', models.IntegerField(blank=True, default=0)),
                ('bad_status', models.IntegerField(blank=True, default=0)),
                ('na_status', models.IntegerField(blank=True, default=0)),
                ('ok_status', models.IntegerField(blank=True, default=0)),
                ('high_status', models.BooleanField(default=False)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chasis_details', to='used_vehicles.usedvehiclejobcard')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Chasis Detail Rows',
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleComplaintDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('complaint_check_box', models.BooleanField(default=False)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('customer_complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.jobcardcomplaintmaster')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_details', to='used_vehicles.usedvehiclejobcard')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Complaint Details',
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleEngineDetailRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=200)),
                ('yes', models.BooleanField(default=False)),
                ('no', models.BooleanField(default=False)),
                ('ok', models.BooleanField(default=False)),
                ('high', models.BooleanField(default=False)),
                ('low', models.BooleanField(default=False)),
                ('area_mention', models.CharField(blank=True, max_length=200)),
                ('yes_status', models.CharField(blank=True, max_length=50)),
                ('no_status', models.CharField(blank=True, max_length=50)),
                ('ok_status', models.CharField(blank=True, max_length=50)),
                ('high_status', models.CharField(blank=True, max_length=50)),
                ('low_status', models.CharField(blank=True, max_length=50)),
                ('mention_status', models.CharField(blank=True, max_length=50)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_details', to='used_vehicles.usedvehiclejobcard')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Engine Detail Rows',
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleLightDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=200)),
                ('yes', models.BooleanField(default=False)),
                ('no', models.BooleanField(default=False)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_details', to='used_vehicles.usedvehiclejobcard')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Light Details',
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleOthersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=200)),
                ('others_check_box', models.BooleanField(default=False)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others_details', to='used_vehicles.usedvehiclejobcard')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Others Details',
            },
        ),
        migrations.CreateModel(
            name='UsedVehiclePartsCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('brake', 'Brake'), ('fork', 'Fork'), ('cables', 'Cables'), ('bulb', 'Bulb'), ('indicator', 'Indicator'), ('rubbers', 'Rubbers'), ('foot_rest', 'Foot Rest'), ('oil_seals', 'Oil Seals'), ('packing', 'Packing'), ('handle_bar', 'Handle Bar and Mount'), ('number_plate', 'Number Plate'), ('chain', 'Chain'), ('clutch', 'Clutch'), ('body_parts', 'Body Parts')], db_index=True, max_length=20)),
                ('spares', models.CharField(blank=True, max_length=200)),
                ('change_need_yes', models.BooleanField(default=False)),
                ('change_need_no', models.BooleanField(default=False)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_check_items', to='used_vehicles.usedvehiclejobcard')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Parts Check Items',
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleSupervisorObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('complaint_check_box', models.BooleanField(default=False)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.jobcardsupervisorobservationmaster')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_observations', to='used_vehicles.usedvehiclejobcard')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Supervisor Observations',
            },
        ),
    ]
