# Generated by Django 6.0.5 on 2026-07-09 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_vehiclesalesorder_order_form_series'),
        ('service', '0008_chasisdetailrow_complaintdetail_enginedetailrow_and_more'),
        ('used_vehicles', '0004_usedvehiclechasisdetailrow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedVehicleMasterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('master_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('has_exchange_vehicle', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='used_vehicles.usedvehiclemastersettings')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exchange_vehicle_id', models.ForeignKey(blank=True, help_text='Reference Link target is a standalone Exchange Vehicle Master, shared with the new-vehicle side; Django has no such freestanding master, so this points directly at sales.ExchangeVehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.exchangevehicle')),
                ('service_settings', models.ForeignKey(blank=True, help_text='Shared with the new-vehicle side -- reuses the existing service.VehicleServiceMaster rather than a duplicate masters-app model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service.vehicleservicemaster')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_settings', to='used_vehicles.usedvehiclemodel')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Master Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleMasterSettingsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('register_number', models.CharField(max_length=50)),
                ('chasis_no', models.CharField(blank=True, help_text='Optional here, unlike the new-vehicle side -- used vehicles are identified primarily by registration number (reference-confirmed asymmetry)', max_length=100, verbose_name='Chasis No')),
                ('engine', models.CharField(max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=20)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='used_vehicles.usedvehiclecolor')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='used_vehicles.usedvehiclemastersettings')),
                ('vehicle_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='used_vehicles.usedvehiclemodel')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Master Settings Items',
            },
        ),
    ]
