# Generated by Django 6.0.5 on 2026-07-10 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_vehicles', '0005_usedvehiclemastersettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedVehicleSalesSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('gst_percent', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Reference marks this field hidden with no client-script consumer; kept as a real editable field here', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Sales Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usedvehicleregisterno',
            name='customer',
            field=models.CharField(blank=True, help_text='Reference types this as free text (Data), not a Link -- preserved as-is', max_length=200),
        ),
        migrations.AddField(
            model_name='usedvehicleregisterno',
            name='status',
            field=models.CharField(blank=True, choices=[('unused', 'Unused'), ('used', 'Used')], max_length=20, verbose_name='Unused/Used Status'),
        ),
        migrations.AddField(
            model_name='usedvehicleregisterno',
            name='vehicle_status',
            field=models.CharField(blank=True, choices=[('used_vehicle', 'Used Vehicle'), ('exchange_vehicle', 'Exchange Vehicle')], max_length=20),
        ),
        migrations.AddField(
            model_name='usedvehicleregisterno',
            name='warehouse_status',
            field=models.CharField(blank=True, choices=[('not_ready', 'Not Ready'), ('maintenance', 'Maintenance'), ('ready_for_sale', 'Ready for Sale')], max_length=20),
        ),
        migrations.CreateModel(
            name='UsedVehicleSalesSettingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Reference computes this via an unreadable server method; kept manually editable here', max_digits=10)),
                ('maintain_cost', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Reference computes this via an unreadable server method; kept manually editable here', max_digits=10)),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Reference computes this via an unreadable server method; kept manually editable here', max_digits=10)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='used_vehicles.usedvehiclesalessetting')),
                ('vehicle_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='used_vehicles.usedvehicleregisterno')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Sales Setting Items',
            },
        ),
    ]
