# Generated by Django 6.0.5 on 2026-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_vehicles', '0006_usedvehiclesalessetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedvehiclesalessettingitem',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Computed as base_rate - (purchase_cost + maintain_cost), matching the reference Client Script formula exactly', max_digits=10),
        ),
    ]
