# Generated by Django 6.0.5 on 2026-07-11 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_vehiclefittingspares_vehiclefittingspareitem'),
        ('used_vehicles', '0007_alter_usedvehiclesalessettingitem_gross_profit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedVehicleInsuranceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('update_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('insurance_status', models.CharField(choices=[('no_insurance', 'Vehicle with No Insurance'), ('expired', 'Vehicle with Expired Insurance')], max_length=20)),
                ('policy_number', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=10)),
                ('from_account', models.CharField(blank=True, help_text='No Chart of Accounts model exists in Django -- free text, matching the accounts_from/accounts_to precedent used throughout', max_length=100)),
                ('to_account', models.CharField(blank=True, max_length=100)),
                ('ref_no', models.CharField(blank=True, max_length=100)),
                ('ref_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='used_vehicles.usedvehicleinsuranceupdate')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('insurance_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.supplier')),
                ('register_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_updates', to='used_vehicles.usedvehicleregisterno')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Insurance Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
