# Generated by Django 6.0.5 on 2026-07-11 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_discountpercentagemaster_ledgercreationdatemaster'),
        ('masters', '0010_vehicletype_normalhelmetmaster'),
        ('spares', '0010_sparesprofitpercentagesettings_and_more'),
        ('used_vehicles', '0008_usedvehicleinsuranceupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usedvehiclecomplaintdetail',
            name='final_inspection',
            field=models.ForeignKey(blank=True, help_text='Phase 10 -- the reference reuses this same child doctype on Final Inspection; exactly one of job_card/final_inspection is set, same dual-FK pattern as spares.SparesIssueAlteration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_table', to='used_vehicles.usedvehiclefinalinspection'),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='additional_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='base_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='delivery_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='exchange_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='finance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='finance_closing',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], max_length=5),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='gst_category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='has_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='item_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='offer_petrol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='petrol_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='petrol_litre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='petrol_type',
            field=models.CharField(blank=True, choices=[('litre', 'Litre'), ('amount', 'Amount')], max_length=10),
        ),
        migrations.AddField(
            model_name='usedvehicledelivery',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.warehouse'),
        ),
        migrations.AddField(
            model_name='usedvehiclefinalinspection',
            name='out_work_charge_form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usedvehiclefinalinspection',
            name='out_work_remarks',
            field=models.CharField(blank=True, help_text='Reference types this as free text (Data) despite the name -- preserved as-is', max_length=255, verbose_name='Bay Out Remarks'),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='used_vehicles.usedvehiclecolor'),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='e_cost',
            field=models.CharField(blank=True, help_text='Reference types this as free text (Data), not a rate -- preserved as-is', max_length=50, verbose_name='Estimation Cost'),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='engine_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='frame_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='p_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='p_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='service',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='total_estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usedvehiclejobcard',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usedvehiclelaborcharge',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usedvehiclelaborcharge',
            name='updated_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usedvehicleoutworkentryreturn',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usedvehicleoutworkentryreturn',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usedvehicleoutworkentryreturn',
            name='payment_status',
            field=models.CharField(blank=True, help_text='Reference types this as free text (Data), not a Select -- preserved as-is', max_length=30),
        ),
        migrations.AddField(
            model_name='usedvehicleoutworkentryreturn',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usedvehicleoutworkentryreturn',
            name='updated_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usedvehiclerchandover',
            name='noc',
            field=models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='NOC'),
        ),
        migrations.AddField(
            model_name='usedvehiclerchandover',
            name='rc_book_received',
            field=models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='usedvehiclerchandover',
            name='to_received',
            field=models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='T.O. Received'),
        ),
        migrations.AddField(
            model_name='usedvehiclerchandover',
            name='vehicle_received',
            field=models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='usedvehiclesupervisorobservation',
            name='final_inspection',
            field=models.ForeignKey(blank=True, help_text='Phase 10 -- same dual-FK pattern as UsedVehicleComplaintDetail above', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_recomment', to='used_vehicles.usedvehiclefinalinspection'),
        ),
        migrations.AlterField(
            model_name='usedvehiclecomplaintdetail',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_details', to='used_vehicles.usedvehiclejobcard'),
        ),
        migrations.AlterField(
            model_name='usedvehiclerchandover',
            name='rc_number',
            field=models.CharField(blank=True, help_text='Also serves as the reference\'s "RC Book Number" field', max_length=100),
        ),
        migrations.AlterField(
            model_name='usedvehiclesupervisorobservation',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_observations', to='used_vehicles.usedvehiclejobcard'),
        ),
        migrations.CreateModel(
            name='UsedVehicleDeliveryAdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('to_account', models.CharField(blank=True, max_length=200)),
                ('draft_type', models.CharField(blank=True, help_text='Reference links to Bank Draft Type Master; no Django equivalent -- free text instead', max_length=100)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='used_vehicles.usedvehicledelivery')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Delivery Advance Payments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('warranty_rsa_amc', models.CharField(blank=True, help_text='Reference uses a Dynamic Link here; no generic Django equivalent -- free text instead', max_length=50)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='used_vehicles.usedvehicledelivery')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Delivery Items',
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleFinalInspectionLaborCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('final_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_charges', to='used_vehicles.usedvehiclefinalinspection')),
                ('labor_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.labourwork')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Final Inspection Labor Charges',
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleFinalInspectionSpareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('qty', models.IntegerField(blank=True, default=1)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('final_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spares_lists', to='used_vehicles.usedvehiclefinalinspection')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spares.sparesitem')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Final Inspection Spare Items',
            },
        ),
        migrations.CreateModel(
            name='UsedVehicleLaborChargeRemoveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_work', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_charge_removes', to='used_vehicles.usedvehiclelaborcharge')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Labor Charge Removed Items',
            },
        ),
        migrations.CreateModel(
            name='UsedVehiclePurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('po_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('required_date', models.DateField()),
                ('target_warehouse', models.CharField(blank=True, help_text='Reference types this as free text (Data) on the PO stage, unlike the real Warehouse Link used later on Receipt/Invoice -- preserved as-is', max_length=200)),
                ('total_quantity', models.IntegerField(blank=True, default=0)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='used_vehicles.usedvehiclepurchaseorder')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_vehicle_purchase_orders', to='accounts.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_vehicle_purchase_orders', to='masters.supplier')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsedVehiclePurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('register_number', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=100)),
                ('chasis_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('noc', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='NOC')),
                ('insurance', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('to_received', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='T.O. Received')),
                ('model', models.CharField(blank=True, max_length=200)),
                ('rc_book_number', models.CharField(blank=True, max_length=100)),
                ('customer', models.CharField(blank=True, max_length=200)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='used_vehicles.usedvehiclecolor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='used_vehicles.usedvehiclepurchaseorder')),
                ('sub_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='used_vehicles.usedvehiclesubgroup')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Purchase Order Items',
            },
        ),
        migrations.CreateModel(
            name='UsedVehiclePurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('required_date', models.DateField()),
                ('total_quantity', models.IntegerField(blank=True, default=0)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('payment_bending_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='used_vehicles.usedvehiclepurchasereceipt')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_vehicle_purchase_receipts', to='accounts.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='used_vehicles.usedvehiclepurchaseorder')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_vehicle_purchase_receipts', to='masters.supplier')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_vehicle_purchase_receipts', to='masters.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Purchase Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usedvehiclepurchaseinvoice',
            name='purchase_receipt',
            field=models.ForeignKey(blank=True, help_text='Optional -- own-purchase trade-ins (no PO/Receipt stage) continue to work with this left blank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='used_vehicles.usedvehiclepurchasereceipt'),
        ),
        migrations.CreateModel(
            name='UsedVehiclePurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('register_number', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=100)),
                ('chasis_number', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, help_text="Reference types this row's color as free text (Data) here, unlike the PO row's real Link -- confirmed live, preserved as-is", max_length=50)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('rc_book_number', models.CharField(blank=True, max_length=100)),
                ('to_received', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='T.O. Received')),
                ('noc', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='NOC')),
                ('insurance', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('customer', models.CharField(blank=True, max_length=200)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='used_vehicles.usedvehiclepurchasereceipt')),
            ],
            options={
                'verbose_name_plural': 'Used Vehicle Purchase Receipt Items',
            },
        ),
    ]
