# Generated by Django 6.0.5 on 2026-07-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_vehicles', '0009_usedvehiclecomplaintdetail_final_inspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedvehiclecomplaintdetail',
            name='final_inspection',
            field=models.ForeignKey(blank=True, help_text="Phase 10 -- the reference reuses this same child doctype on Final Inspection. Exactly one of job_card/final_inspection is set in practice -- enforced by which inline formset a row is created through (see used_vehicles/forms.py), not a model clean() check: Django sets an inline formset child's FK only at save() time, after formset.is_valid() already ran, so a clean()-level exactly-one-set check would reject every legitimate new row before the FK is ever assigned.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_table', to='used_vehicles.usedvehiclefinalinspection'),
        ),
        migrations.AlterField(
            model_name='usedvehiclesupervisorobservation',
            name='final_inspection',
            field=models.ForeignKey(blank=True, help_text='Phase 10 -- same dual-FK pattern as UsedVehicleComplaintDetail above, same reason for not enforcing exactly-one-set via clean()', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_recomment', to='used_vehicles.usedvehiclefinalinspection'),
        ),
    ]
