# Generated by Django 6.0.1 on 2026-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_vehicles', '0011_alter_usedvehicleoutworkentryreturn_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedvehiclepurchaseinvoice',
            name='cash_account',
            field=models.CharField(blank=True, help_text='No Chart of Accounts model exists in Django -- free text, matching the from_account/to_account free-text fallback convention used elsewhere (e.g. UsedVehicleInsuranceUpdate)', max_length=100),
        ),
        migrations.AddField(
            model_name='usedvehiclepurchaseinvoice',
            name='invoice_no',
            field=models.CharField(blank=True, help_text="Mandatory in the reference spec (06_Used_Vehicle_Purchase.md) -- the supplier's own invoice number, distinct from this record's auto-generated invoice_number. Left blank=True here for additive-migration safety; enforced required in the form.", max_length=100, verbose_name='Invoice No'),
        ),
    ]
