# Generated by Django 6.0.1 on 2026-07-17 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_vehicles', '0012_usedvehiclepurchaseinvoice_cash_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usedvechilercbookissue',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='used_vehicles.usedvechilercbookissue'),
        ),
        migrations.AddField(
            model_name='usedvechilercbookissue',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvechilercbookissue',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedvechilercbookissue',
            name='docstatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='usedvechilercbookissue',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvechilercbookissue',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedvehiclerchandover',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='used_vehicles.usedvehiclerchandover'),
        ),
        migrations.AddField(
            model_name='usedvehiclerchandover',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvehiclerchandover',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedvehiclerchandover',
            name='docstatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='usedvehiclerchandover',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedvehiclerchandover',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
