# Generated by Django 6.0.5 on 2026-05-17 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_source', models.CharField(blank=True, choices=[('walk_in', 'Walk In'), ('phone', 'Phone'), ('website', 'Website'), ('referral', 'Referral'), ('social', 'Social Media')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('follow_up', 'Follow Up'), ('converted', 'Converted'), ('lost', 'Lost')], default='open', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='customers.bikemodel')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='accounts.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='customers.customer')),
                ('sales_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('purpose', models.CharField(blank=True, choices=[('test_ride', 'Test Ride'), ('discussion', 'Discussion'), ('showroom_visit', 'Showroom Visit'), ('delivery', 'Delivery')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='sales.salesenquiry')),
            ],
            options={
                'verbose_name_plural': 'Sales Appointments',
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_notes', models.TextField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_feedback_created', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='sales.salesenquiry')),
            ],
            options={
                'verbose_name_plural': 'Sales Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_status', models.CharField(choices=[('booked', 'Booked'), ('invoiced', 'Invoiced'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='accounts.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='customers.customer')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.salesenquiry')),
                ('sales_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='customers.vehiclestock')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Sales Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('valuation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_vehicle', to='sales.vehiclesalesorder')),
            ],
            options={
                'verbose_name_plural': 'Exchange Vehicles',
            },
        ),
    ]
