# Generated by Django 6.0.1 on 2026-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_vehicledelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesenquiry',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('follow_up', 'Follow Up'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='sales_status',
            field=models.CharField(choices=[('booked', 'Booked'), ('invoiced', 'Invoiced'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='booked', max_length=20),
        ),
    ]
