# Generated by Django 6.0.1 on 2026-05-25 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("sales", "0003_alter_salesenquiry_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclesalesorder",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_orders",
                to="customers.vehiclestock",
            ),
        ),
    ]
