# Generated by Django 6.0.1 on 2026-05-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0004_alter_vehiclesalesorder_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesenquiry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='customers.customer'),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('enquiry_source', models.CharField(blank=True, choices=[('walk_in', 'Walk In'), ('phone', 'Phone'), ('website', 'Website'), ('referral', 'Referral'), ('social', 'Social Media')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_of_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='customers.bikemodel')),
            ],
            options={
                'verbose_name_plural': 'Prospects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='sales.prospect'),
        ),
    ]
