# Generated by Django 6.0.1 on 2026-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_vehicleallotment_vehiclefitting'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledelivery',
            name='checklist_accessories',
            field=models.BooleanField(default=False, verbose_name='Accessories Fitted & Verified'),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='checklist_insurance',
            field=models.BooleanField(default=False, verbose_name='Insurance Policy Handed Over'),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='checklist_rc_book',
            field=models.BooleanField(default=False, verbose_name='RC Book / Temp Reg Handed Over'),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='checklist_toolkit',
            field=models.BooleanField(default=False, verbose_name='Toolkit & Owner Manual Handed Over'),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='checklist_warranty',
            field=models.BooleanField(default=False, verbose_name='Warranty Card Handed Over'),
        ),
    ]
