# Generated by Django 6.0.1 on 2026-06-04 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0007_vehicledelivery_checklist_accessories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDIChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('engine_oil_level', models.BooleanField(default=False)),
                ('coolant_level', models.BooleanField(default=False)),
                ('brake_fluid_level', models.BooleanField(default=False)),
                ('chain_tension', models.BooleanField(default=False)),
                ('chain_lubrication', models.BooleanField(default=False)),
                ('tyre_pressure_front', models.BooleanField(default=False)),
                ('tyre_pressure_rear', models.BooleanField(default=False)),
                ('brake_front_working', models.BooleanField(default=False)),
                ('brake_rear_working', models.BooleanField(default=False)),
                ('clutch_adjustment', models.BooleanField(default=False)),
                ('throttle_smooth', models.BooleanField(default=False)),
                ('battery_voltage', models.BooleanField(default=False)),
                ('headlight_working', models.BooleanField(default=False)),
                ('taillight_working', models.BooleanField(default=False)),
                ('indicators_working', models.BooleanField(default=False)),
                ('horn_working', models.BooleanField(default=False)),
                ('speedometer_working', models.BooleanField(default=False)),
                ('kill_switch_working', models.BooleanField(default=False)),
                ('paint_no_scratches', models.BooleanField(default=False)),
                ('all_panels_fitted', models.BooleanField(default=False)),
                ('mirrors_adjusted', models.BooleanField(default=False)),
                ('seat_firm', models.BooleanField(default=False)),
                ('toolkit_present', models.BooleanField(default=False)),
                ('owners_manual_present', models.BooleanField(default=False)),
                ('invoice_ready', models.BooleanField(default=False)),
                ('insurance_done', models.BooleanField(default=False)),
                ('form20_submitted', models.BooleanField(default=False)),
                ('temporary_registration', models.BooleanField(default=False)),
                ('overall_remarks', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdi_approvals', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdi_checklist', to='sales.vehiclesalesorder')),
            ],
            options={
                'verbose_name': 'PDI Checklist',
            },
        ),
        migrations.CreateModel(
            name='TestRideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=200)),
                ('rider_phone', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_odometer', models.IntegerField(default=0)),
                ('end_odometer', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('out', 'Vehicle Out'), ('returned', 'Vehicle Returned'), ('cancelled', 'Cancelled')], default='out', max_length=20)),
                ('feedback_after_ride', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accompanied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_rides_accompanied', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_rides_created', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_rides', to='sales.salesenquiry')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_rides', to='customers.vehiclestock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_enquiries', models.IntegerField(default=0)),
                ('target_test_rides', models.IntegerField(default=0)),
                ('target_conversions', models.IntegerField(default=0)),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets_created', to=settings.AUTH_USER_MODEL)),
                ('sales_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('sales_executive', 'month', 'year')},
            },
        ),
    ]
