# Generated by Django 6.0.5 on 2026-06-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_pdichecklist_testridelog_salestarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesappointment',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesappointment',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', verbose_name='Cancellation / Postpone Reason'),
        ),
        migrations.AddField(
            model_name='salesappointment',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesappointment',
            name='is_cancelled_postponed',
            field=models.BooleanField(default=False, verbose_name='Appointment Cancel/Postponed'),
        ),
        migrations.AddField(
            model_name='salesappointment',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesappointment',
            name='vehicle_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='salesappointment',
            name='whatsapp_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesfeedback',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='sales.salesappointment', verbose_name='Sales Appointment'),
        ),
        migrations.AddField(
            model_name='salesfeedback',
            name='feed_back_date',
            field=models.DateField(blank=True, null=True, verbose_name='Feedback Date'),
        ),
        migrations.AddField(
            model_name='salesfeedback',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesfeedback',
            name='vehicle_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Vehicle Code'),
        ),
        migrations.AlterField(
            model_name='salesfeedback',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Feed Back Follow Date'),
        ),
    ]
