# Generated by Django 6.0.1 on 2026-06-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesappointment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesenquiry',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='expected_purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Purchase Date'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Purpose'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='whatsapp_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp No'),
        ),
    ]
