# Generated by Django 6.0.5 on 2026-06-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesenquiry_erp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesappointment',
            name='vehicle_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Vehicle Code'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='address_line3',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Address 3'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='address_line4',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Address 4'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='customer_enquiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Customer Enquiry Date'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='customer_interested_in_exchange',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, verbose_name='Customer Interested in Exchange'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Corporate', 'Corporate'), ('Fleet', 'Fleet')], default='', max_length=50, verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='enquiry_type',
            field=models.CharField(blank=True, choices=[('New Vehicle', 'New Vehicle'), ('Exchange', 'Exchange'), ('Fleet', 'Fleet'), ('Corporate', 'Corporate')], default='', max_length=50, verbose_name='Enquiry Type'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Finance', 'Finance'), ('Exchange', 'Exchange')], default='', max_length=50, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='source_of_information',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Source of Information'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='test_ride_taken',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, verbose_name='Test Ride Taken'),
        ),
        migrations.CreateModel(
            name='SalesEnquiryCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Unique ID')),
                ('call_from', models.CharField(blank=True, default='', max_length=200, verbose_name='Call From')),
                ('bill_sec', models.IntegerField(default=0, verbose_name='Bill Sec')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('audio_url', models.URLField(blank=True, default='', verbose_name='Audio URL')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='sales.salesenquiry')),
            ],
            options={
                'verbose_name': 'Call Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesEnquiryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(verbose_name='Update Date')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Follow Up', 'Follow Up'), ('Converted', 'Converted'), ('Lost', 'Lost'), ('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=50, verbose_name='Status')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='sales.salesenquiry')),
            ],
            options={
                'verbose_name': 'Enquiry History',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesFeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=500, verbose_name='Points')),
                ('feedback_type', models.CharField(blank=True, choices=[('Product', 'Product'), ('Price', 'Price'), ('Service', 'Service'), ('Competitor', 'Competitor'), ('Finance', 'Finance'), ('Other', 'Other')], default='', max_length=100, verbose_name='Type')),
                ('response', models.TextField(blank=True, default='', verbose_name='Response')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Rating')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='sales.salesfeedback')),
            ],
            options={
                'verbose_name': 'Feedback Item',
                'ordering': ['id'],
            },
        ),
    ]
