# Generated by Django 6.0.1 on 2026-06-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_erp_alignment_enquiry_calllog_history_feedback_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangevehicle',
            name='rc_handed_over',
            field=models.BooleanField(default=False, verbose_name='RC Book Handed Over'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='rc_handover_date',
            field=models.DateField(blank=True, null=True, verbose_name='RC Handover Date'),
        ),
    ]
