# Generated by Django 6.0.5 on 2026-06-24 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_supplier_more_fields'),
        ('sales', '0012_exchangevehicle_rc_handover'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangevehicle',
            name='chassis_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chassis No'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='colour',
            field=models.CharField(blank=True, max_length=50, verbose_name='Colour'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='engine_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Engine Number'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='hp_endorsement',
            field=models.BooleanField(default=False, verbose_name='HP Endorsement'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='insurance_valid_upto',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance Valid Upto'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='manufacturing_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Manufacturing Company'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='sub_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sub Group'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_vehicles', to='masters.warehouse', verbose_name='Target Warehouse'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='vehicle_category',
            field=models.CharField(blank=True, choices=[('motorcycle', 'Motorcycle'), ('scooter', 'Scooter'), ('moped', 'Moped'), ('other', 'Other')], max_length=20, verbose_name='Vehicle Category'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='year_of_make',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Make'),
        ),
    ]
