# Generated by Django 6.0.5 on 2026-07-08 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_bunkname_financecompany'),
        ('sales', '0013_exchangevehicle_chassis_no_exchangevehicle_colour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledelivery',
            name='additional_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='sales.vehicledelivery'),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='bunk_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.bunkname'),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='docstatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='finance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='finance_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='issue_gate_pass',
            field=models.BooleanField(default=False, verbose_name='Issue Gate Pass'),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='manager_approval_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='offer_petrol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('completed', 'Completed')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='petrol_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='petrol_litre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='petrol_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='sales_order_additional_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='table_charges_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicledelivery',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclefitting',
            name='item_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehiclefitting',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity Count'),
        ),
        migrations.AddField(
            model_name='vehiclefitting',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Item Rate'),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='additional_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rollup of advance_payments lines', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='sales.vehiclesalesorder'),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='balance_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='balance_sales_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='customer_refund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='default_helmet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date'),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='delivery_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='docstatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='exchange_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='finance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='finance_closing',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='gst_category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='has_vehicle_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='helmet_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='helmet_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='insurance_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_sales_orders', to='masters.supplier', verbose_name='Insurance Name'),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='is_finance_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='number_plate_amount',
            field=models.DecimalField(decimal_places=2, default=330, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=30, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('completed', 'Completed')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='sales_finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='masters.financecompany', verbose_name='Sales Finance'),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='special_helmet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='special_helmet_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.warehouse', verbose_name='Special Helmet Warehouse'),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='table_charges_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='temp_area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='temp_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='temp_charges_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sales.vehiclesalesorder'),
        ),
        migrations.AlterField(
            model_name='vehiclefitting',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Item Amount'),
        ),
        migrations.AlterField(
            model_name='vehiclefitting',
            name='fitting_name',
            field=models.CharField(max_length=200, verbose_name='Item Name'),
        ),
        migrations.CreateModel(
            name='AdditionalVehicleFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='QTY')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fittings', to='sales.vehiclesalesorder')),
            ],
            options={
                'verbose_name_plural': 'Additional Vehicle Fittings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteAdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('to_account', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='sales.vehicledelivery')),
            ],
            options={
                'verbose_name_plural': 'Delivery Note Advance Payments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('warranty_rsa_amc', models.CharField(choices=[('warranty', 'Warranty'), ('rsa', 'RSA'), ('amc', 'AMC'), ('none', 'None')], default='none', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.vehicledelivery')),
            ],
            options={
                'verbose_name_plural': 'Delivery Note Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNotePaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode_of_payment', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_entries', to='sales.vehicledelivery')),
            ],
            options={
                'verbose_name_plural': 'Delivery Note Payment Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderAdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(blank=True, max_length=100)),
                ('draft_type', models.CharField(blank=True, max_length=100, verbose_name='Draft/Bank Type')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('to_account', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='sales.vehiclesalesorder')),
            ],
            options={
                'verbose_name_plural': 'Sales Order Advance Payments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.vehiclesalesorder')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Sale Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _backfill_order_numbers(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]


def _backfill_order_numbers(apps, schema_editor):
    VehicleSalesOrder = apps.get_model('sales', 'VehicleSalesOrder')
    for i, order in enumerate(VehicleSalesOrder.objects.order_by('id'), start=1):
        order.order_number = f'ORD-{i:05d}'
        order.save(update_fields=['order_number'])
