# Generated by Django 6.0.5 on 2026-07-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_vehicledelivery_additional_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalvehiclefitting',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, verbose_name='QTY'),
        ),
        migrations.AlterField(
            model_name='additionalvehiclefitting',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='additionalvehiclefitting',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverynoteadvancepayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverynotepaymententry',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderadvancepayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='additional_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='finance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='invoice_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='petrol_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='petrol_litre',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='sales_order_additional_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='table_charges_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicledelivery',
            name='total_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehiclefitting',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Item Amount'),
        ),
        migrations.AlterField(
            model_name='vehiclefitting',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, verbose_name='Quantity Count'),
        ),
        migrations.AlterField(
            model_name='vehiclefitting',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Item Rate'),
        ),
        migrations.AlterField(
            model_name='vehiclesaleitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesaleitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesaleitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='additional_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Rollup of advance_payments lines', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='balance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='balance_sales_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='customer_refund',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='delivery_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='exchange_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='finance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='helmet_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='invoice_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='number_plate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=330, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='table_charges_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='temp_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclesalesorder',
            name='total_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
