# Generated by Django 6.0.5 on 2026-07-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_orderformseries_orderformsettings'),
        ('sales', '0015_alter_additionalvehiclefitting_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesalesorder',
            name='order_form_series',
            field=models.ForeignKey(blank=True, help_text='Optional link to a pre-generated Order Form Series number; order_number above remains the working numbering mechanism', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='masters.orderformseries', verbose_name='Order Form Series'),
        ),
    ]
