# Generated by Django 6.0.5 on 2026-07-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_vehiclesalesorder_order_form_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesenquiry',
            name='exchange_customer_expected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='exchange_original_rc_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='exchange_owner_type',
            field=models.CharField(blank=True, choices=[('First Owner', 'First Owner'), ('Second Owner', 'Second Owner'), ('Third Owner', 'Third Owner')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='exchange_price_offer_by_dealer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='exchange_type',
            field=models.CharField(blank=True, choices=[('Yamaha', 'Yamaha'), ('Competition', 'Competition')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='exchange_valid_insurance',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='exchange_vehicle_model_and_make',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='salesenquiry',
            name='exchange_year_of_manufacturing',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
