# Generated by Django 6.0.5 on 2026-07-12 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_discountpercentagemaster_ledgercreationdatemaster'),
        ('masters', '0010_vehicletype_normalhelmetmaster'),
        ('sales', '0017_salesenquiry_exchange_customer_expected_price_and_more'),
        ('used_vehicles', '0010_alter_usedvehiclecomplaintdetail_final_inspection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=200, unique=True)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('gst_category', models.CharField(blank=True, choices=[('unregistered', 'Unregistered'), ('registered_regular', 'Registered Regular')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_type', models.CharField(blank=True, max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('citytown', models.CharField(blank=True, max_length=100, verbose_name='City/Town')),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='accounts.branch', verbose_name='Area')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='masters.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Dealers',
                'ordering': ['dealer_name'],
            },
        ),
        migrations.CreateModel(
            name='DealerRCHandOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('handover_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='sales.dealerrchandover')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rc_hand_overs', to='sales.dealer')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dealer RC Hand Overs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerRCHandOverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noc', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='NOC')),
                ('to_received', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='T.O. Received')),
                ('rc_book_received', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('vehicle_received', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('rc_book_number', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.dealerrchandover')),
                ('register_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealer_rc_handover_items', to='used_vehicles.usedvehicleregisterno')),
            ],
            options={
                'verbose_name_plural': 'Dealer RC Hand Over Items',
            },
        ),
        migrations.CreateModel(
            name='ExchangeDealerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('payment_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=10, verbose_name='Pay Type')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('pending_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(blank=True, help_text='Reference types this as free text (Data), not a Select -- preserved as-is', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='sales.exchangedealerpayment')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_dealer_payments', to='accounts.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.dealer')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exchange Dealer Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeDealerPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(blank=True, max_length=200)),
                ('vehicle_amount', models.DecimalField(decimal_places=2, default=0, help_text='Reference types this as free text (Data) but the header total_amount clearly sums it -- built as a real Decimal, same "fix an obviously mistyped reference field" call made elsewhere this session', max_digits=10)),
                ('allow_permission', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='sales.exchangedealerpayment')),
                ('register_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealer_payment_items', to='used_vehicles.usedvehicleregisterno')),
            ],
            options={
                'verbose_name_plural': 'Exchange Dealer Payment Items',
            },
        ),
        migrations.CreateModel(
            name='ExchangeVehicleDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], db_index=True, default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_no', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('hp_endorsement', models.BooleanField(default=False, help_text='Confirmed live as a batch-level field with no per-vehicle child equivalent')),
                ('insurance_received', models.BooleanField(default=False, help_text='Confirmed live as a batch-level field with no per-vehicle child equivalent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='sales.exchangevehicledealer')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_vehicle_dealer_transfers', to='accounts.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_transfers', to='sales.dealer')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_vehicle_dealer_transfers_out', to='masters.warehouse')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_vehicle_dealer_transfers_in', to='masters.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Exchange Vehicle Dealer Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exchangedealerpayment',
            name='exchange_vehicle_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.exchangevehicledealer'),
        ),
        migrations.CreateModel(
            name='ExchangeVehicleDealerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(blank=True, help_text="Reference links to 'Exchange Master Used Vehicle Names' -- confirmed 0 records, no real Django master needed -- free text instead", max_length=200)),
                ('engine_number', models.CharField(blank=True, max_length=100)),
                ('party_name', models.CharField(blank=True, help_text="Reference types this row's own field as free text (Data), not a Link -- preserved as-is", max_length=200)),
                ('rc_book_received', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('rc_book_number', models.CharField(blank=True, max_length=100)),
                ('noc', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='NOC')),
                ('to_received', models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='T.O Received')),
                ('vehicle_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('color', models.CharField(blank=True, help_text='Reference links to Product Color; no Django master exists anywhere -- free text instead', max_length=50)),
                ('vehicle_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('vehicle_code', models.CharField(max_length=100)),
                ('registration_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_transfer_items', to='used_vehicles.usedvehicleregisterno')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='sales.exchangevehicledealer')),
            ],
            options={
                'verbose_name_plural': 'Exchange Vehicle Dealer Items',
            },
        ),
    ]
