# Generated by Django 6.0.7 on 2026-07-14 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_dealer_dealerrchandover_dealerrchandoveritem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedealerpaymentitem',
            name='vehicle_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reference types this as free text (Data) but the header total_amount clearly sums it -- built as a real Decimal, same "fix an obviously mistyped reference field" call made elsewhere this session', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
