# Generated by Django 6.0.7 on 2026-07-16 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_exchangedealerpaymentitem_vehicle_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesaleitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehiclesaleitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
