# Generated by Django 6.0.1 on 2026-07-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_vehiclesaleitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangevehicle',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Balance Amount'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='finance_closing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Finance Closing Amount'),
        ),
        migrations.AddField(
            model_name='exchangevehicle',
            name='finance_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Finance Company'),
        ),
    ]
